version: "3.8"

services:
  db:
    image: "postgres:13.4"
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=artbox
      - POSTGRES_PASSWORD=artbox
      - POSTGRES_DB=artbox

volumes:
  pgdata: {}
